version: '3.1'

services:

  db:
    image: postgres:9.6
    restart: always
    environment:
      POSTGRES_DB: alfrescoaio
      POSTGRES_USER: alfresco
      POSTGRES_PASSWORD: alfresco
    ports:
      - 5432:5432


  adminer:
    image: adminer
    restart: always
    ports:
      - 8070:8080

  solr6:
      image: alfresco/alfresco-search-services:1.1.0
      environment:
          #Solr needs to know how to register itself with Alfresco
          - SOLR_ALFRESCO_HOST=host.docker.internal
          - SOLR_ALFRESCO_PORT=8080
          #Alfresco needs to know how to call solr
          - SOLR_SOLR_HOST=solr6
          - SOLR_SOLR_PORT=8983
          #Create the default alfresco and archive cores
          - SOLR_CREATE_ALFRESCO_DEFAULTS=alfresco,archive
      ports:
          - 8983:8983 #Browser port